[build]
  publish = "client/out"
  # Temporary: use install instead of ci until package-lock.json includes swiper
  command = "npm --prefix client install && npm --prefix client run build"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/shop.html"
  to = "/shop"
  status = 301

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301

# Redirect legacy /site/*.html to clean routes
[[redirects]]
  from = "/site/:page.html"
  to = "/:page"
  status = 301
  force = true

[[redirects]]
  from = "/site/index.html"
  to = "/"
  status = 301
  force = true

# Default locale redirects (clean routes → /en/*)
[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/en/about"
  status = 301
  force = true

[[redirects]]
  from = "/shop"
  to = "/en/shop"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/en/contact"
  status = 301
  force = true
