backend:
  name: git-gateway
  branch: main

media_folder: "site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages (builder)"
    files:
      - label: "Home"
        name: "home"
        file: "site/content/pages/home.json"
        format: "json"
        fields:
          - { label: "Hero Title", name: "hero.title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero.subtitle", widget: "text", required: false }
          - { label: "Hero Background", name: "hero.background_image", widget: "string", required: false }
          - { label: "About Title", name: "about.title", widget: "string" }
          - { label: "About Body", name: "about.body", widget: "text" }

  - name: "products"
    label: "Products"
    file: "site/content/products.json"
    fields:
      - label: "Items"
        name: "items"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Price (EUR)", name: "price", widget: "number" }
          - { label: "Image", name: "image", widget: "string" }
          - { label: "Link", name: "link", widget: "string", required: false }

  - name: "faqs"
    label: "FAQs"
    file: "site/content/faqs.json"
    fields:
      - label: "FAQ Items"
        name: "items"
        widget: "list"
        fields:
          - { label: "Question", name: "q", widget: "string" }
          - { label: "Answer", name: "a", widget: "text" }

