backend:
  name: git-gateway
  branch: main

media_folder: "site/images/uploads"
public_folder: "/images/uploads"

collections:
  # ---- Default language (fallback) pages with the SECTION BUILDER ----
  - name: "pages"
    label: "Pages (builder)"
    folder: "site/content/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text", required: false }
              - { label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left" }
              - { label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false }
              - { label: "CTA label", name: "cta_label", widget: "string", required: false }
              - { label: "CTA link", name: "cta_link", widget: "string", required: false }

          - label: "Text Block"
            name: "text"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Body", name: "body", widget: "text" }
              - { label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left" }

          - label: "Product Grid"
            name: "productGrid"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Source file (e.g. products.json)", name: "source", widget: "string", default: "products.json" }
              - { label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50 }

          - label: "FAQs"
            name: "faqs"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Source file (e.g. faqs.json)", name: "source", widget: "string", default: "faqs.json" }

          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Button label", name: "button_label", widget: "string", required: false }
              - { label: "Button link", name: "button_link", widget: "string", required: false }
              - { label: "Background image (use /images/... or upload)", name: "background_image", widget: "string" }

          - label: "Video"
            name: "video"
            widget: "object"
            fields:
              - { label: "YouTube URL", name: "youtube_url", widget: "string" }
              - { label: "Caption text", name: "caption", widget: "string", required: false }

  # ---- English pages (same builder) ----
  - name: "pages_en"
    label: "Pages (EN)"
    folder: "site/content/en/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - { label: "Hero", name: "hero", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Subtitle", name: "subtitle", widget: "text", required: false},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false},
                {label: "CTA label", name: "cta_label", widget: "string", required: false},
                {label: "CTA link", name: "cta_link", widget: "string", required: false}
          ] }
          - { label: "Text Block", name: "text", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Body", name: "body", widget: "text"},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
          ] }
          - { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "products.json"},
                {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
          ] }
          - { label: "FAQs", name: "faqs", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
          ] }
          - { label: "Banner", name: "banner", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Button label", name: "button_label", widget: "string", required: false},
                {label: "Button link", name: "button_link", widget: "string", required: false},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string"}
          ] }
          - { label: "Video", name: "video", widget: "object", fields: [
                {label: "YouTube URL", name: "youtube_url", widget: "string"},
                {label: "Caption text", name: "caption", widget: "string", required: false}
          ] }

  # ---- Portuguese pages (same builder) ----
  - name: "pages_pt"
    label: "Pages (PT)"
    folder: "site/content/pt/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - { label: "Hero", name: "hero", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Subtitle", name: "subtitle", widget: "text", required: false},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false},
                {label: "CTA label", name: "cta_label", widget: "string", required: false},
                {label: "CTA link", name: "cta_link", widget: "string", required: false}
          ] }
          - { label: "Text Block", name: "text", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Body", name: "body", widget: "text"},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
          ] }
          - { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "products.json"},
                {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
          ] }
          - { label: "FAQs", name: "faqs", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
          ] }
          - { label: "Banner", name: "banner", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Button label", name: "button_label", widget: "string", required: false},
                {label: "Button link", name: "button_link", widget: "string", required: false},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string"}
          ] }
          - { label: "Video", name: "video", widget: "object", fields: [
                {label: "YouTube URL", name: "youtube_url", widget: "string"},
                {label: "Caption text", name: "caption", widget: "string", required: false}
          ] }

  # ---- Spanish pages (same builder) ----
  - name: "pages_es"
    label: "Pages (ES)"
    folder: "site/content/es/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - { label: "Hero", name: "hero", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Subtitle", name: "subtitle", widget: "text", required: false},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false},
                {label: "CTA label", name: "cta_label", widget: "string", required: false},
                {label: "CTA link", name: "cta_link", widget: "string", required: false}
          ] }
          - { label: "Text Block", name: "text", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Body", name: "body", widget: "text"},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
          ] }
          - { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "products.json"},
                {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
          ] }
          - { label: "FAQs", name: "faqs", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
          ] }
          - { label: "Banner", name: "banner", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Button label", name: "button_label", widget: "string", required: false},
                {label: "Button link", name: "button_link", widget: "string", required: false},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string"}
          ] }
          - { label: "Video", name: "video", widget: "object", fields: [
                {label: "YouTube URL", name: "youtube_url", widget: "string"},
                {label: "Caption text", name: "caption", widget: "string", required: false}
          ] }
