backend:
  name: git-gateway
  branch: main

media_folder: "site/static/uploads"
public_folder: "/uploads"

i18n:
  structure: single_file
  locales: [en, pt, es]
  default_locale: en

collections:
  # ---- Default language (fallback) pages with the SECTION BUILDER ----
  - name: "pages"
    label: "Pages (builder)"
    folder: "site/content/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Status", name: "status", widget: "select", options: ["published", "draft"], default: "published" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text", required: false }
              - { label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left" }
              - { label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false }
              - { label: "CTA label", name: "cta_label", widget: "string", required: false }
              - { label: "CTA link", name: "cta_link", widget: "string", required: false }

          - label: "Text Block"
            name: "text"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Body", name: "body", widget: "text" }
              - { label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left" }

          - label: "Product Grid"
            name: "productGrid"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Source file (e.g. products.json)", name: "source", widget: "string", default: "products.json" }
              - { label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50 }

          - label: "FAQs"
            name: "faqs"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Source file (e.g. faqs.json)", name: "source", widget: "string", default: "faqs.json" }

          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Button label", name: "button_label", widget: "string", required: false }
              - { label: "Button link", name: "button_link", widget: "string", required: false }
              - { label: "Background image (use /images/... or upload)", name: "background_image", widget: "string" }

          - label: "Video"
            name: "video"
            widget: "object"
            fields:
              - { label: "YouTube URL", name: "youtube_url", widget: "string" }
              - { label: "Caption text", name: "caption", widget: "string", required: false }

  # ---- English pages (same builder) ----
  - name: "pages_en"
    label: "Pages (EN)"
    folder: "site/content/en/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Status", name: "status", widget: "select", options: ["published", "draft"], default: "published" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - { label: "Hero", name: "hero", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Subtitle", name: "subtitle", widget: "text", required: false},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false},
                {label: "CTA label", name: "cta_label", widget: "string", required: false},
                {label: "CTA link", name: "cta_link", widget: "string", required: false}
          ] }
          - { label: "Text Block", name: "text", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Body", name: "body", widget: "text"},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
          ] }
          - { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "products.json"},
                {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
          ] }
          - { label: "FAQs", name: "faqs", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
          ] }
          - { label: "Banner", name: "banner", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Button label", name: "button_label", widget: "string", required: false},
                {label: "Button link", name: "button_link", widget: "string", required: false},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string"}
          ] }
          - { label: "Video", name: "video", widget: "object", fields: [
                {label: "YouTube URL", name: "youtube_url", widget: "string"},
                {label: "Caption text", name: "caption", widget: "string", required: false}
          ] }

  # ---- Portuguese pages (same builder) ----
  - name: "pages_pt"
    label: "Pages (PT)"
    folder: "site/content/pt/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Status", name: "status", widget: "select", options: ["published", "draft"], default: "published" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - { label: "Hero", name: "hero", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Subtitle", name: "subtitle", widget: "text", required: false},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false},
                {label: "CTA label", name: "cta_label", widget: "string", required: false},
                {label: "CTA link", name: "cta_link", widget: "string", required: false}
          ] }
          - { label: "Text Block", name: "text", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Body", name: "body", widget: "text"},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
          ] }
          - { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "products.json"},
                {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
          ] }
          - { label: "FAQs", name: "faqs", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
          ] }
          - { label: "Banner", name: "banner", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Button label", name: "button_label", widget: "string", required: false},
                {label: "Button link", name: "button_link", widget: "string", required: false},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string"}
          ] }
          - { label: "Video", name: "video", widget: "object", fields: [
                {label: "YouTube URL", name: "youtube_url", widget: "string"},
                {label: "Caption text", name: "caption", widget: "string", required: false}
          ] }

  # ---- Spanish pages (same builder) ----
  - name: "pages_es"
    label: "Pages (ES)"
    folder: "site/content/es/pages"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Status", name: "status", widget: "select", options: ["published", "draft"], default: "published" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - { label: "Hero", name: "hero", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Subtitle", name: "subtitle", widget: "text", required: false},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string", required: false},
                {label: "CTA label", name: "cta_label", widget: "string", required: false},
                {label: "CTA link", name: "cta_link", widget: "string", required: false}
          ] }

  # ---- Products (folder-based entries) ----
  - name: "products"
    label: "Products"
    folder: "site/content/products"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Status", name: "status", widget: "select", options: ["published", "draft"], default: "published" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Sizes"
        name: "sizes"
        widget: "list"
        field: { label: "Size", name: "size", widget: "string" }
      - label: "Prices"
        name: "prices"
        widget: "list"
        field: { label: "Price (EUR)", name: "price", widget: "number" }
      - label: "Images"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
      - label: "Badges"
        name: "badges"
        widget: "list"
        field: { label: "Badge", name: "badge", widget: "string" }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Display Order", name: "order", widget: "number", required: false, default: 0 }
      - { label: "Active", name: "active", widget: "boolean", default: true }

  - name: "faqs"
    label: "FAQs"
    folder: "site/content/faqs"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    i18n:
      structure: multiple_folders
    fields:
      - { label: "Status", name: "status", widget: "select", options: ["published", "draft"], default: "published" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Question", name: "question", widget: "string", i18n: translate }
      - { label: "Answer", name: "answer", widget: text, i18n: translate }
      - { label: "Category", name: "category", widget: string, required: false, i18n: translate }
      - { label: "Order", name: "order", widget: number, required: false, default: 0, i18n: duplicate }
      - { label: "Active", name: "active", widget: boolean, default: true, i18n: duplicate }
          - { label: "Text Block", name: "text", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Body", name: "body", widget: "text"},
                {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
          ] }
          - { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "products.json"},
                {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
          ] }
          - { label: "FAQs", name: "faqs", widget: "object", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
          ] }
          - { label: "Banner", name: "banner", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Button label", name: "button_label", widget: "string", required: false},
                {label: "Button link", name: "button_link", widget: "string", required: false},
                {label: "Background image (use /images/... or upload)", name: "background_image", widget: "string"}
          ] }
          - { label: "Video", name: "video", widget: "object", fields: [
                {label: "YouTube URL", name: "youtube_url", widget: "string"},
                {label: "Caption text", name: "caption", widget: "string", required: false}
          ] }
