backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "About Page"
    files:
      - label: "About"
        name: "about"
        file: "content/about.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body",  name: "body",  widget: "text" }
          - { label: "Image (optional path)", name: "image", widget: "string", required: false }
