backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "About Page"
    files:
      - label: "About"
        name: "about"
        file: "content/about.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body",  name: "body",  widget: "text" }
          - { label: "Image (optional path)", name: "image", widget: "string", required: false }

  - name: "faqs"
    label: "FAQs"
    files:
      - label: "FAQs"
        name: "faqs"
        file: "content/faqs.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Question", name: "q", widget: "string" }
              - { label: "Answer",   name: "a", widget: "text" }

  - name: "products"
    label: "Products"
    files:
      - label: "Products"
        name: "products"
        file: "content/products.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Slug",  name: "slug",  widget: "string" }
              - { label: "Name",  name: "name",  widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Image", name: "image", widget: "string" }
              - { label: "Link",  name: "link",  widget: "string" }
