backend:
  name: git-gateway
  branch: main

media_folder: "site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages (builder)"
    files:
      - label: "Home"
        name: "home"
        file: "site/content/pages/home.json"
        format: "json"
        fields:
          - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
          - label: "Sections"
            name: "sections"
            widget: "list"
            types:
              - { label: "Hero", name: "hero", widget: "object", fields: [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Subtitle", name: "subtitle", widget: "text", required: false},
                    {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"},
                    {label: "Background image", name: "background_image", widget: "string", required: false},
                    {label: "CTA label", name: "cta_label", widget: "string", required: false},
                    {label: "CTA link", name: "cta_link", widget: "string", required: false}
                ] }
              - { label: "Text Block", name: "text", widget: "object", fields: [
                    {label: "Heading", name: "heading", widget: "string"},
                    {label: "Body", name: "body", widget: "text"},
                    {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
                ] }
              - { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Source file", name: "source", widget: "string", default: "products.json"},
                    {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
                ] }
              - { label: "FAQs", name: "faqs", widget: "object", fields: [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
                ] }
              - { label: "Banner", name: "banner", widget: "object", fields: [
                    {label: "Heading", name: "heading", widget: "string"},
                    {label: "Button label", name: "button_label", widget: "string", required: false},
                    {label: "Button link", name: "button_link", widget: "string", required: false},
                    {label: "Background image", name: "background_image", widget: "string"}
                ] }
              - { label: "Video", name: "video", widget: "object", fields: [
                    {label: "YouTube URL", name: "youtube_url", widget: "string"},
                    {label: "Caption text", name: "caption", widget: "string", required: false}
                ] }

      - label: "About"
        name: "about"
        file: "site/content/pages/about.json"
        format: "json"
        fields:
          - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
          - { label: "Sections", name: "sections", widget: "list", types: [
                { label: "Text Block", name: "text", widget: "object", fields: [
                    {label: "Heading", name: "heading", widget: "string"},
                    {label: "Body", name: "body", widget: "text"},
                    {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
                ] }
            ] }

      - label: "Shop"
        name: "shop"
        file: "site/content/pages/shop.json"
        format: "json"
        fields:
          - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
          - { label: "Sections", name: "sections", widget: "list", types: [
                { label: "Product Grid", name: "productGrid", widget: "object", fields: [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Source file", name: "source", widget: "string", default: "products.json"},
                    {label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50}
                ] }
            ] }

      - label: "Contact"
        name: "contact"
        file: "site/content/pages/contact.json"
        format: "json"
        fields:
          - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
          - { label: "Sections", name: "sections", widget: "list", types: [
                { label: "Text Block", name: "text", widget: "object", fields: [
                    {label: "Heading", name: "heading", widget: "string"},
                    {label: "Body", name: "body", widget: "text"},
                    {label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left"}
                ] }
            ] }

      - label: "FAQs page"
        name: "faqsPage"
        file: "site/content/pages/faqs.json"
        format: "json"
        fields:
          - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
          - { label: "Sections", name: "sections", widget: "list", types: [
                { label: "FAQs", name: "faqs", widget: "object", fields: [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Source file", name: "source", widget: "string", default: "faqs.json"}
                ] }
            ] }

  - name: "pages_en"
    label: "Pages (EN)"
    folder: "site/content/en/pages"
    create: true
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "pages_pt"
    label: "Pages (PT)"
    folder: "site/content/pt/pages"
    create: true
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "pages_es"
    label: "Pages (ES)"
    folder: "site/content/es/pages"
    create: true
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Take over page", name: "takeover", widget: "boolean", default: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  # ---- FIXED: use files: [...] for single-file collections ----
  - name: "products"
    label: "Products"
    files:
      - label: "Product List"
        name: "product_list"
        file: "site/content/products.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Price (€)", name: "price", widget: "number", min: 0 }
              - { label: "Image (path)", name: "image", widget: "string" }
              - { label: "Product URL", name: "url", widget: "string" }

  - name: "faqs"
    label: "FAQs"
    files:
      - label: "FAQ Entries"
        name: "faq_entries"
        file: "site/content/faqs.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Question", name: "q", widget: "string" }
              - { label: "Answer", name: "a", widget: "text" }
