backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages (builder)"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.json"
        format: "json"
        fields:
          - label: "Sections"
            name: "sections"
            widget: "list"
            types:
              - label: "Hero"
                name: "hero"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Subtitle", name: "subtitle", widget: "text" }
                  - { label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left" }
                  - { label: "Background image", name: "background_image", widget: "string", required: false }
                  - { label: "CTA label", name: "cta_label", widget: "string", required: false }
                  - { label: "CTA link", name: "cta_link", widget: "string", required: false }

              - label: "Text Block"
                name: "text"
                widget: "object"
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Body", name: "body", widget: "text" }
                  - { label: "Align", name: "align", widget: "select", options: ["left","center","right"], default: "left" }

              - label: "Product Grid"
                name: "productGrid"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Source file", name: "source", widget: "string", default: "products.json" }
                  - { label: "How many", name: "count", widget: "number", default: 6, min: 1, max: 50 }

              - label: "FAQs"
                name: "faqs"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Source file", name: "source", widget: "string", default: "faqs.json" }

              - label: "Banner"
                name: "banner"
                widget: "object"
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Button label", name: "button_label", widget: "string", required: false }
                  - { label: "Button link", name: "button_link", widget: "string", required: false }
                  - { label: "Background image", name: "background_image", widget: "string" }

              - label: "Video"
                name: "video"
                widget: "object"
                fields:
                  - { label: "YouTube URL", name: "youtube_url", widget: "string" }
                  - { label: "Caption text", name: "caption", widget: "string", required: false }
